#ifndef __AV_VIVO_H__
#define __AV_VIVO_H__

#define FRAME_RATE_DEFAULT 25


HI_S32 HI3521_Comm_VoPubConfig(VO_DEV s32VoDev, HI_S32 s32priority);
HI_S32 HI3521_Comm_ViInit(SAMPLE_VI_MODE_E enViMode,VIDEO_NORM_E enNorm);
HI_S32 HI3521_VoTest(HI_VOID);
HI_S32 HI3521_Comm_VO_BindVoWbc(VO_DEV VoWbcDev, VO_LAYER VoLayer, VO_CHN VoChn);
HI_S32 HI3521_Comm_VO_StartWbc(VO_WBC VoWbc,const VO_WBC_ATTR_S *pstWbcAttr);
HI_S32 HI3521_Comm_WBC_End(HI_VOID);
HI_S32 HI3521_Comm_WBC_BindVo(VO_WBC VoWbc,VO_WBC_SOURCE_S *pstWbcSource);
HI_S32 HI3521_Comm_VO_BindVpss(VO_LAYER VoLayer,VO_CHN VoChn,VPSS_GRP VpssGrp,VPSS_CHN VpssChn);
HI_S32 HI3521_Comm_WBC_Start(HI_VOID);
HI_S32 HI3521_Comm_VI_Mode2Param(SAMPLE_VI_MODE_E enViMode, SAMPLE_VI_PARAM_S *pstViParam);
HI_S32 HI3521_Comm_VpssConfig(HI_S32 s32ChnStart,HI_S32 s32VpssGrpCnt,VIDEO_NORM_E enNorm,SAMPLE_VI_MODE_E enViMode);
HI_S32 HI3521_Comm_VENC_BindVpss(VENC_CHN VeChn,VPSS_GRP VpssGrp,VPSS_CHN VpssChn);
HI_S32 HI3521_Comm_VDEC_BindVpss(VDEC_CHN VdChn, VPSS_GRP VpssGrp);
HI_S32 HI3521_Comm_VDEC_UnBindVpss(VDEC_CHN VdChn, VPSS_GRP VpssGrp);
HI_S32 HI3521_Comm_VDEC_UnBindVo(VDEC_CHN VdChn, VO_LAYER VoLayer, VO_CHN VoChn);
HI_S32 HI3521_Comm_Vo_SwitchMode(VO_LAYER VoLayer,SAMPLE_VO_MODE_E enPreVoMode,SAMPLE_VO_MODE_E enVoMode);
HI_S32 HI3521_Comm_VPSS_Start(HI_S32 s32ChnStart,HI_S32 s32GrpCnt, SIZE_S *pstSize, HI_S32 s32ChnCnt,VPSS_GRP_ATTR_S *pstVpssGrpAttr);
HI_S32 HI3521_Comm_VO_UnBindVpss(VO_LAYER VoLayer,VO_CHN VoChn,VPSS_GRP VpssGrp,VPSS_CHN VpssChn);
HI_S32 HI3521_Comm_VO_BindVi(VO_LAYER VoLayer, VO_CHN VoChn, VI_CHN ViChn);
HI_S32 HI3521_Comm_VO_UnBindVi(VO_LAYER VoLayer, VO_CHN VoChn, VI_CHN ViChn);
HI_S32 HI3521_Comm_VO_StartChn(VO_LAYER VoLayer, SAMPLE_VO_MODE_E enMode);
HI_S32 HI3521_Comm_ViStop(SAMPLE_VI_MODE_E enViMode);
HI_S32 HI3521_Comm_VENC_Stop(VENC_CHN VencChn);
HI_S32 HI3521_Comm_VDEC_BindVo(VDEC_CHN VdChn, VO_LAYER VoLayer, VO_CHN VoChn);
HI_S32 HI3521_COMM_VENC_UnBindVpss(VENC_CHN VeChn,VPSS_GRP VpssGrp,VPSS_CHN VpssChn);

#endif
